//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GlobalResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.GlobalResources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string AreaAdminViewIndexAction {
            get {
                return ResourceManager.GetString("AreaAdminViewIndexAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        internal static string AreaAdminViewIndexEmail {
            get {
                return ResourceManager.GetString("AreaAdminViewIndexEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string AreaAdminViewIndexUsername {
            get {
                return ResourceManager.GetString("AreaAdminViewIndexUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this?.
        /// </summary>
        internal static string AreaModeratorViewDeleteText {
            get {
                return ResourceManager.GetString("AreaModeratorViewDeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save game..
        /// </summary>
        internal static string AreaModeratorViewPartialSaveGame {
            get {
                return ResourceManager.GetString("AreaModeratorViewPartialSaveGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your cart is empty, add some games first.
        /// </summary>
        internal static string ControllerOrderCheckOutErrorText {
            get {
                return ResourceManager.GetString("ControllerOrderCheckOutErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order was created successful!.
        /// </summary>
        internal static string ControllerOrderCheckOutSuccsessText {
            get {
                return ResourceManager.GetString("ControllerOrderCheckOutSuccsessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has been removed from your shopping cart..
        /// </summary>
        internal static string ControllerShoppingCartRemoveMessage {
            get {
                return ResourceManager.GetString("ControllerShoppingCartRemoveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart (.
        /// </summary>
        internal static string ViewCartSummaryCart {
            get {
                return ResourceManager.GetString("ViewCartSummaryCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error..
        /// </summary>
        internal static string ViewError {
            get {
                return ResourceManager.GetString("ViewError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing your request..
        /// </summary>
        internal static string ViewErrorText {
            get {
                return ResourceManager.GetString("ViewErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete order.
        /// </summary>
        internal static string ViewGameCheckOutSubmitText {
            get {
                return ResourceManager.GetString("ViewGameCheckOutSubmitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re just one step away to get your games..
        /// </summary>
        internal static string ViewGameCheckOutText {
            get {
                return ResourceManager.GetString("ViewGameCheckOutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string ViewGameDelete {
            get {
                return ResourceManager.GetString("ViewGameDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        internal static string ViewGamesDetailsDescription {
            get {
                return ResourceManager.GetString("ViewGamesDetailsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Trailer:.
        /// </summary>
        internal static string ViewGamesDetailsGameTrailer {
            get {
                return ResourceManager.GetString("ViewGamesDetailsGameTrailer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price:.
        /// </summary>
        internal static string ViewGamesDetailsPrice {
            get {
                return ResourceManager.GetString("ViewGamesDetailsPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Date:.
        /// </summary>
        internal static string ViewGamesDetailsReleaseDate {
            get {
                return ResourceManager.GetString("ViewGamesDetailsReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size:.
        /// </summary>
        internal static string ViewGamesDetailsSize {
            get {
                return ResourceManager.GetString("ViewGamesDetailsSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string ViewGamesEdit {
            get {
                return ResourceManager.GetString("ViewGamesEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string ViewHomeIndexNext {
            get {
                return ResourceManager.GetString("ViewHomeIndexNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to cart.
        /// </summary>
        internal static string ViewHomeIndexPartialAddToCart {
            get {
                return ResourceManager.GetString("ViewHomeIndexPartialAddToCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string ViewHomeIndexPartialDescription {
            get {
                return ResourceManager.GetString("ViewHomeIndexPartialDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string ViewHomeIndexPartialDetails {
            get {
                return ResourceManager.GetString("ViewHomeIndexPartialDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string ViewHomeIndexPartialPrice {
            get {
                return ResourceManager.GetString("ViewHomeIndexPartialPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        internal static string ViewHomeIndexPrevious {
            get {
                return ResourceManager.GetString("ViewHomeIndexPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string ViewHomeIndexSearch {
            get {
                return ResourceManager.GetString("ViewHomeIndexSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string ViewHomeIndexTitle {
            get {
                return ResourceManager.GetString("ViewHomeIndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found Games.
        /// </summary>
        internal static string ViewHomeSearchFoundGames {
            get {
                return ResourceManager.GetString("ViewHomeSearchFoundGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No games to show..
        /// </summary>
        internal static string ViewHomeSearchNoGamesToShow {
            get {
                return ResourceManager.GetString("ViewHomeSearchNoGamesToShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Results For.
        /// </summary>
        internal static string ViewHomeSearchSearchingResult {
            get {
                return ResourceManager.GetString("ViewHomeSearchSearchingResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Game.
        /// </summary>
        internal static string ViewLayoutAddGame {
            get {
                return ResourceManager.GetString("ViewLayoutAddGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        internal static string ViewLayoutAdmin {
            get {
                return ResourceManager.GetString("ViewLayoutAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string ViewLayoutHome {
            get {
                return ResourceManager.GetString("ViewLayoutHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock out..
        /// </summary>
        internal static string ViewLockOut {
            get {
                return ResourceManager.GetString("ViewLockOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account has been locked out, please try again later..
        /// </summary>
        internal static string ViewLockOutText {
            get {
                return ResourceManager.GetString("ViewLockOutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello .
        /// </summary>
        internal static string ViewLoginPartialHello {
            get {
                return ResourceManager.GetString("ViewLoginPartialHello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string ViewLoginPartialLogin {
            get {
                return ResourceManager.GetString("ViewLoginPartialLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogOff.
        /// </summary>
        internal static string ViewLoginPartialLogOff {
            get {
                return ResourceManager.GetString("ViewLoginPartialLogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        internal static string ViewLoginPartialSignUp {
            get {
                return ResourceManager.GetString("ViewLoginPartialSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check out now!.
        /// </summary>
        internal static string ViewShoppingCartIndexCheckOutNow {
            get {
                return ResourceManager.GetString("ViewShoppingCartIndexCheckOutNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        internal static string ViewShoppingCartIndexCount {
            get {
                return ResourceManager.GetString("ViewShoppingCartIndexCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game.
        /// </summary>
        internal static string ViewShoppingCartIndexGame {
            get {
                return ResourceManager.GetString("ViewShoppingCartIndexGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string ViewShoppingCartIndexPrice {
            get {
                return ResourceManager.GetString("ViewShoppingCartIndexPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from cart.
        /// </summary>
        internal static string ViewShoppingCartIndexRemoveFromCart {
            get {
                return ResourceManager.GetString("ViewShoppingCartIndexRemoveFromCart", resourceCulture);
            }
        }
    }
}
